# Generated by Django 5.0.4 on 2024-04-19 07:16

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='BillingAddress',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('billing_society', models.CharField(blank=True, max_length=100, null=True)),
                ('billing_email', models.EmailField(max_length=254, null=True)),
                ('billing_address', models.CharField(max_length=200, null=True)),
                ('billing_city', models.CharField(max_length=55, null=True)),
                ('billing_country', models.CharField(max_length=55, null=True)),
                ('billing_phone_office', models.CharField(max_length=55, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('payment_type', models.CharField(blank=True, max_length=55, null=True)),
                ('payment_date', models.DateField(blank=True, null=True)),
                ('payment_heure', models.TimeField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('url_image', models.URLField(null=True)),
                ('price', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('quantity', models.SmallIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Tracking',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tracking_method', models.CharField(blank=True, max_length=55, null=True)),
                ('tracking_carrier', models.CharField(blank=True, max_length=55, null=True)),
                ('tracking_number', models.CharField(blank=True, max_length=55, null=True)),
                ('tracking_url', models.URLField(blank=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marketplace', models.CharField(choices=[('amazon', 'amazon'), ('cdiscount', 'cdiscount')], max_length=55)),
                ('order_id', models.CharField(blank=True, max_length=55, null=True)),
                ('order_purchase_date', models.DateField(blank=True, null=True)),
                ('order_purchase_heure', models.TimeField(blank=True, null=True)),
                ('order_amount', models.DecimalField(blank=True, decimal_places=1, max_digits=10, null=True)),
                ('billing_address', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.billingaddress')),
                ('order_payment', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.payment')),
                ('products', models.ManyToManyField(related_name='cart', to='orders.product')),
                ('tracking_informations', models.OneToOneField(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='order', to='orders.tracking')),
            ],
        ),
    ]
